# Generated by Django 6.0.2 on 2026-04-15 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_like_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pin_post',
            field=models.ManyToManyField(blank=True, related_name='blog_posts_pin_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
