# Generated by Django 6.0.2 on 2026-04-21 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_pin_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_post',
            field=models.ManyToManyField(blank=True, related_name='blog_savedposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
