# Generated by Django 6.0.2 on 2026-04-22 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_saved_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='saved_post',
            field=models.ManyToManyField(blank=True, related_name='blog_savedPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
