# Generated by Django 6.0.2 on 2026-04-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='Activity',
            field=models.ManyToManyField(blank=True, related_name='activity_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
