# Generated by Django 6.0.2 on 2026-04-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_activity_post_post_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Activity',
        ),
    ]
